# Generated by Django 4.2.16 on 2025-02-23 09:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего входа')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон')),
                ('address_pvz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адресс ПВЗ')),
                ('delivery', models.CharField(blank=True, choices=[('SDEK', 'SDEK'), ('Mail', 'Почта'), ('Yandex', 'Яндекс'), ('Boxberry', 'Боксберри')], default='SDEK', max_length=150, null=True, verbose_name='Способ доставки')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
