# Generated by Django 4.2.4 on 2025-02-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_markup_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_pvz',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delivery',
        ),
    ]
