# Generated by Django 4.2.4 on 2025-02-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_global_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='global_percentage',
        ),
    ]
