# Generated by Django 4.2.16 on 2025-02-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_remove_supplier_product'),
        ('product', '0004_remove_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
