# Generated by Django 4.2.16 on 2025-02-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость товаров поставщика'),
        ),
    ]
