# Generated by Django 4.2.16 on 2025-02-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_supplier_is_visible'),
        ('product', '0006_product_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
