# Generated by Django 4.2.4 on 2025-02-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Окончательная цена'),
            preserve_default=False,
        ),
    ]
