# Generated by Django 4.2.4 on 2025-02-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
    ]
