# Generated by Django 4.2.16 on 2025-02-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
    ]
