# Generated by Django 4.2.16 on 2025-02-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_remove_supplier_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_visible',
        ),
    ]
