# Generated by Django 4.2.16 on 2025-02-23 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент наценки')),
                ('dollar_exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Курс доллара')),
            ],
            options={
                'verbose_name': 'Глобальная настройка',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
    ]
