# Generated by Django 4.2.4 on 2025-02-25 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='dollar_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Курс доллара'),
        ),
    ]
