# Generated by Django 4.2.4 on 2025-02-25 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_alter_globalsettings_dollar_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='dollar_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Курс доллара'),
        ),
    ]
