# Generated by Django 4.2.4 on 2025-02-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_globalsettings_markup_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='markup_percentage',
            new_name='global_mark_up',
        ),
    ]
