# Generated by Django 4.2.4 on 2025-02-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_rename_markup_percentage_globalsettings_global_mark_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Глобальная настройка', 'verbose_name_plural': 'Глобальная настройка'},
        ),
    ]
