# Generated by Django 4.2.4 on 2025-02-25 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0006_alter_globalsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='global_mark_up',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Общий процент наценки'),
        ),
    ]
