# Generated by Django 4.2.4 on 2025-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0007_alter_globalsettings_global_mark_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Текущая дата'),
        ),
    ]
