# Generated by Django 4.2.16 on 2025-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
    ]
