# Generated by Django 4.2.4 on 2025-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_pvz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адресс ПВЗ'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('SDEK', 'SDEK'), ('Mail', 'Почта'), ('Yandex', 'Яндекс'), ('Boxberry', 'Боксберри')], default='SDEK', max_length=150, null=True, verbose_name='Способ доставки'),
        ),
    ]
