# Generated by Django 4.2.4 on 2025-02-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_address_pvz_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_pvz',
            field=models.CharField(default=1, max_length=150, verbose_name='Адресс ПВЗ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('SDEK', 'SDEK'), ('Mail', 'Почта'), ('Yandex', 'Яндекс'), ('Boxberry', 'Боксберри')], default='SDEK', max_length=150, verbose_name='Способ доставки'),
        ),
    ]
