# Generated by Django 4.2.4 on 2025-03-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_address_pvz_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Цена за единицу'),
            preserve_default=False,
        ),
    ]
