# Generated by Django 4.2.4 on 2025-03-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_unit',
        ),
    ]
