# Generated by Django 4.2.4 on 2025-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Итоговая стоимость заказа'),
            preserve_default=False,
        ),
    ]
